name: carv_generators
description: >-
  Code generation package for Carv App which works combinely with `carv_annotations` package.
version: 1.0.0
repository: https://github.com/carv-app/carv_generators

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  build:
  source_gen: 
  carv_annotations: ^1.0.0

dev_dependencies:
  test:
  build_runner:
  build_verify:
  source_gen_test: